/**
 * @file communication/dto/email-audit.dto.ts
 *
 * DTOs for creating and updating EmailAudit records.
 * These are internal to the Communication module — never sent over HTTP.
 */

import type { EmailStatus } from '../types/email.types';
import type { UserId } from '../../../shared/types/index';

/** DTO used when a listener creates the initial PENDING audit record. */
export interface CreateEmailAuditDto {
  readonly id:        string;    // UUID v4 — pre-generated by listener
  readonly eventId:   string;    // UUID v4 — idempotency key from event payload
  readonly eventName: string;    // AUTH_EVENTS constant string
  readonly userId:    UserId;
  readonly toEmail:   string;
  readonly status:    'PENDING';
  readonly requestId: string;    // trace ID
  readonly createdAt: string;    // ISO 8601
}

/** DTO used when updating status after send attempt. */
export interface UpdateEmailStatusDto {
  readonly status:             'SENT' | 'FAILED' | 'SKIPPED';
  readonly providerMessageId?: string;   // present on SENT
  readonly sentAt?:            string;   // ISO 8601 — present on SENT
  readonly failReason?:        string;   // present on FAILED
  readonly failedAt?:          string;   // ISO 8601 — present on FAILED
}
