import {
  LayoutDashboard,
  ShoppingBag,
  Calendar,
  Package,
  Image as ImageIcon,
  Users,
  UserPlus,
  Settings,
  FileText,
  Menu,
  X,
  Home,
  AlertTriangle,
  ShieldAlert,
  RotateCcw,
  Save,
  Sparkles,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  Bell,
  Trash2,
  CheckCheck,
  Loader2,
  Loader,
  TrendingUp,
  TrendingDown,
  Search,
  SlidersHorizontal,
  RefreshCw,
  BellOff,
  Terminal,
  CreditCard,
  Truck,
  Pen,
  CheckSquare,
  Square,
  CheckCircle,
  CheckCircle2,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Bookmark,
  Copy,
  Clock,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Share2,
  Mail,
  MapPin,
  Phone,
  Moon,
  Sun,
  Languages,
  ShoppingCart,
  User,
  ShieldCheck,
  Star,
  PlusCircle,
  Plus,
  Minus,
  Award,
  Tag,
  Info,
  Gift,
  QrCode,
  Edit2,
  Folder,
  Play,
  LayoutGrid,
  List,
  PanelLeft,
  Command,
  LogOut,
  Eye,
  EyeOff,
  BadgeCheck,
  Check,
  Paperclip,
  Heart,
  Headphones,
  Lock,
  Camera,
  RefreshCcw,
  DollarSign,
  HelpCircle,
  Layers,
  Percent,
  Compass,
  Globe,
  Coins,
  Store,
  Sliders,
  Palette,
  Box,
  ClipboardList,
  Paintbrush,
  Milk,
  Leaf,
  Recycle,
  GripVertical,
  CornerDownRight,
  ArrowUp,
  ArrowDown,
  FolderPlus,
  Laptop,
  Smartphone,
  BookOpen,
  Download,
  Upload,
  Flame,
  Sprout,
  HeartHandshake,
  UploadCloud,
  Crop,
  Maximize,
  Minimize,
} from 'lucide-react';
import React from 'react';

interface CustomIconProps extends React.ComponentPropsWithoutRef<'svg'> {
  size?: number | string;
  strokeWidth?: number | string;
}

export const Facebook = React.forwardRef<SVGSVGElement, CustomIconProps>(({ size = 24, strokeWidth = 2, className, ...props }, ref) =>
  React.createElement('svg', {
    ref,
    xmlns: 'http://www.w3.org/2000/svg',
    width: size,
    height: size,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth,
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    className,
    ...props
  }, React.createElement('path', { d: 'M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z' }))
);
Facebook.displayName = 'Facebook';

export const Twitter = React.forwardRef<SVGSVGElement, CustomIconProps>(({ size = 24, strokeWidth = 2, className, ...props }, ref) =>
  React.createElement('svg', {
    ref,
    xmlns: 'http://www.w3.org/2000/svg',
    width: size,
    height: size,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth,
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    className,
    ...props
  }, React.createElement('path', { d: 'M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z' }))
);
Twitter.displayName = 'Twitter';

export const Linkedin = React.forwardRef<SVGSVGElement, CustomIconProps>(({ size = 24, strokeWidth = 2, className, ...props }, ref) =>
  React.createElement('svg', {
    ref,
    xmlns: 'http://www.w3.org/2000/svg',
    width: size,
    height: size,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth,
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    className,
    ...props
  },
    React.createElement('path', { d: 'M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z' }),
    React.createElement('rect', { x: '2', y: '9', width: '4', height: '12' }),
    React.createElement('circle', { cx: '4', cy: '4', r: '2' })
  )
);
Linkedin.displayName = 'Linkedin';

export const Instagram = React.forwardRef<SVGSVGElement, CustomIconProps>(({ size = 24, strokeWidth = 2, className, ...props }, ref) =>
  React.createElement('svg', {
    ref,
    xmlns: 'http://www.w3.org/2000/svg',
    width: size,
    height: size,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    strokeWidth,
    strokeLinecap: 'round',
    strokeLinejoin: 'round',
    className,
    ...props
  },
    React.createElement('rect', { x: '2', y: '2', width: '20', height: '20', rx: '5', ry: '5' }),
    React.createElement('path', { d: 'M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z' }),
    React.createElement('line', { x1: '17.5', y1: '6.5', x2: '17.51', y2: '6.5' })
  )
);
Instagram.displayName = 'Instagram';

export const ICON_REGISTRY = {
  dashboard: LayoutDashboard,
  products: ShoppingBag,
  orders: FileText,
  fileText: FileText,
  events: Calendar,
  calendar: Calendar,
  package: Package,
  blogs: FileText,
  gallery: ImageIcon,
  image: ImageIcon,
  managers: Users,
  settings: Settings,
  menu: Menu,
  close: X,
  home: Home,
  alert: AlertTriangle,
  rotate: RotateCcw,
  sparkles: Sparkles,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronDown: ChevronDown,
  bell: Bell,
  trash: Trash2,
  save: Save,
  checkDouble: CheckCheck,
  loading: Loader2,
  search: Search,
  filter: SlidersHorizontal,
  refresh: RefreshCw,
  bellOff: BellOff,
  lock: Lock,
  terminal: Terminal,
  creditCard: CreditCard,
  truck: Truck,
  edit: Pen,
  edit2: Edit2,
  checkSquare: CheckSquare,
  square: Square,
  checkCircle: CheckCircle,
  checkCircle2: CheckCircle2,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  bookmark: Bookmark,
  facebook: Facebook,
  twitter: Twitter,
  linkedin: Linkedin,
  instagram: Instagram,
  copy: Copy,
  clock: Clock,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpRight: ArrowUpRight,
  share: Share2,
  mail: Mail,
  mapPin: MapPin,
  phone: Phone,
  moon: Moon,
  sun: Sun,
  languages: Languages,
  cart: ShoppingCart,
  user: User,
  shieldCheck: ShieldCheck,
  star: Star,
  plusCircle: PlusCircle,
  plus: Plus,
  minus: Minus,
  award: Award,
  tag: Tag,
  info: Info,
  gift: Gift,
  qrCode: QrCode,
  folder: Folder,
  play: Play,
  grid: LayoutGrid,
  list: List,
  panelLeft: PanelLeft,
  command: Command,
  logout: LogOut,
  eye: Eye,
  eyeOff: EyeOff,
  verified: BadgeCheck,
  check: Check,
  file: Paperclip,
  heart: Heart,
  headphones: Headphones,
  camera: Camera,
  refreshCcw: RefreshCcw,
  dollar: DollarSign,
  help: HelpCircle,
  layers: Layers,
  percent: Percent,
  compass: Compass,
  globe: Globe,
  coins: Coins,
  store: Store,
  sliders: Sliders,
  palette: Palette,
  box: Box,
  clipboardList: ClipboardList,
  paintbrush: Paintbrush,
  users: Users,
  chevronsUpDown: ChevronsUpDown,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  loader: Loader,
  userPlus: UserPlus,
  milk: Milk,
  leaf: Leaf,
  recycle: Recycle,
  gripVertical: GripVertical,
  cornerDownRight: CornerDownRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  folderPlus: FolderPlus,
  laptop: Laptop,
  smartphone: Smartphone,
  bookOpen: BookOpen,
  download: Download,
  upload: Upload,
  flame: Flame,
  sprout: Sprout,
  heartHandshake: HeartHandshake,
  uploadCloud: UploadCloud,
  crop: Crop,
  maximize: Maximize,
  minimize: Minimize,
  shieldAlert: ShieldAlert,
} as const;


