/**
 * @file communication/services/template.service.ts
 *
 * Renders English Handlebars email templates.
 *
 * All templates are in templates/en/{name}.hbs.
 * Emails are sent in English only — locale is NOT used for template
 * selection (the payload locale field is accepted but ignored here).
 *
 * Design notes:
 * - Subject lines live in a typed map indexed by template name.
 *   No DB round-trip, no i18n plugin dependency.
 * - Compiled Handlebars templates are cached in memory on first load.
 * - Plain-text fallback is auto-generated by stripping HTML tags.
 * - FRONTEND_URL is injected via ConfigService (not hardcoded).
 *
 * If multi-locale support is needed in future:
 *   1. Add locale subdirectories: templates/{locale}/{name}.hbs
 *   2. Restore locale parameter in resolveSubject() + renderHtml()
 *   3. Add locale-keyed entries to EMAIL_SUBJECTS
 */

import { Injectable, Logger } from '@nestjs/common';
import * as fs from 'fs';
import * as path from 'path';
import * as Handlebars from 'handlebars';
import { ConfigService } from '@nestjs/config';
import type { EmailTemplateName, TemplateContext, TemplateRenderResult } from '../types/email.types';
import { COMM_ERROR_CODES } from '../constants/comm-error-codes.constant';

// ─────────────────────────────────────────────────────────────────────────────
// Subject line map — English only
// ─────────────────────────────────────────────────────────────────────────────

const EMAIL_SUBJECTS: Record<EmailTemplateName, string> = {
  'welcome':                    'Welcome to MeriGauMata!',
  'password-reset':             'Reset Your MeriGauMata Password',
  'otp':                        'Your MeriGauMata Verification Code',
  'magic-link':                 'Your MeriGauMata Sign-In Link',
  '2fa-code':                   'Your MeriGauMata Two-Factor Code',
  '2fa-enabled':                'Two-Factor Authentication Enabled — MeriGauMata',
  'google-linked':              'Google Account Linked to MeriGauMata',
  'account-locked':             '⚠️ Your MeriGauMata Account Has Been Locked',
  'account-unlocked':           'Your MeriGauMata Account Has Been Unlocked',
  'suspicious-login':           '🔐 New Sign-In Detected on Your MeriGauMata Account',
  'suspicious-login-high-risk': '🚨 High-Risk Sign-In — Your MeriGauMata Session Was Revoked',
  'email-change':               'Verify Your New Email Address — MeriGauMata',
};


// Handlebars compiled template function type
type HbsTemplate = (context: Record<string, unknown>) => string;

@Injectable()
export class TemplateService {
  private readonly logger = new Logger(TemplateService.name);
  private readonly templateCache = new Map<string, HbsTemplate>();
  private readonly templatesDir: string;

  constructor(private readonly config: ConfigService) {
    // Works in both ts-node (src/) and compiled (dist/) because __dirname
    // always resolves relative to this file's location.
    this.templatesDir = path.resolve(__dirname, '../templates/en');
  }

  /**
   * Renders the English Handlebars template for the given template name.
   *
   * @param template - Which email template to render
   * @param _locale  - Accepted but unused; reserved for future multi-locale support
   * @param context  - Strictly typed template variables
   */
  async render(
    template: EmailTemplateName,
    _locale:  string,        // ignored — English only
    context:  TemplateContext,
  ): Promise<TemplateRenderResult> {
    const subject = EMAIL_SUBJECTS[template];
    const html    = await this.renderHtml(template, context);
    const text    = this.htmlToPlainText(html);
    return { subject, html, text };
  }

  // ── Private helpers ────────────────────────────────────────────────────────

  private async renderHtml(
    template: EmailTemplateName,
    context:  TemplateContext,
  ): Promise<string> {
    const compiledTemplate = await this.loadTemplate(template);

    if (!compiledTemplate) {
      this.logger.error(
        { commErrorCode: COMM_ERROR_CODES.TEMPLATE_NOT_FOUND.code, template },
        `TemplateService: ${COMM_ERROR_CODES.TEMPLATE_NOT_FOUND.message}`,
      );
      throw new Error(
        `${COMM_ERROR_CODES.TEMPLATE_NOT_FOUND.code}: template '${template}' not found`,
      );
    }

    try {
      const frontendUrl = this.config.get<string>('FRONTEND_URL', 'https://merigaumata.com');

      return compiledTemplate({
        ...context,
        year:        new Date().getFullYear(),
        frontendUrl,
        // Build full URL from token for password-reset template
        resetUrl: context.resetToken
          ? `${frontendUrl}/reset-password?token=${context.resetToken}`
          : undefined,
        // Build full URL from token for email-change template
        verifyUrl: context.verifyToken
          ? `${frontendUrl}/verify-email?token=${context.verifyToken}`
          : undefined,
      } as Record<string, unknown>);
    } catch (err: unknown) {
      const reason = err instanceof Error ? err.message : String(err);
      this.logger.error(
        { commErrorCode: COMM_ERROR_CODES.TEMPLATE_RENDER_FAILED.code, template, reason },
        `TemplateService: ${COMM_ERROR_CODES.TEMPLATE_RENDER_FAILED.message}`,
      );
      throw new Error(`${COMM_ERROR_CODES.TEMPLATE_RENDER_FAILED.code}: ${reason}`);
    }
  }

  /**
   * Loads and caches a compiled Handlebars template.
   * Returns null if the file does not exist.
   */
  private async loadTemplate(template: EmailTemplateName): Promise<HbsTemplate | null> {
    const cached = this.templateCache.get(template);
    if (cached) return cached;

    const filePath = path.join(this.templatesDir, `${template}.hbs`);
    if (!fs.existsSync(filePath)) return null;

    const source   = await fs.promises.readFile(filePath, 'utf8');
    const compiled = Handlebars.compile(source, { noEscape: false }) as HbsTemplate;
    this.templateCache.set(template, compiled);
    return compiled;
  }

  /** Strips HTML tags and decodes basic entities for the plain-text fallback. */
  private htmlToPlainText(html: string): string {
    return html
      .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
      .replace(/<[^>]+>/g, ' ')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&nbsp;/g, ' ')
      .replace(/\s{2,}/g, ' ')
      .trim();
  }
}
